version: '3'
services:
  db:
    image: docker.netsoc.co/public/mysql:dev-env
    container_name: netsoc-mysql
    ports:
      - 3306:3306
  auth:
    image: docker.netsoc.co/public/ldap:dev-env
    container_name: netsoc-ldap
    ports:
      - 389:389
  consul:
    image: consul:1.4.4
    container_name: netsoc-consul
    environment:
      CONSUL_BIND_INTERFACE: eth0 # ???
    ports:
      - 8500:8500
      - 8600:53/udp
      - 8400:8400